#!/usr/bin/env node

//run chmod +x yahtzee 
// from root directory, gives this file executable permissions

const commands = require('./bin/commands')

const cmd = process.argv[2]
const id = process.argv[3]
const name = process.argv[4]

switch (cmd) {

  case 'list':
    commands.list()
    break

  case 'del':
    commands.del(id)
    break

  case 'edit':
    commands.editName(id, name)
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}